require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SchoolDaysController do

  # This should return the minimal set of attributes required to create a valid
  # SchoolDay. As you add validations to SchoolDay, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SchoolDaysController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all school_days as @school_days" do
      school_day = SchoolDay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:school_days).should eq([school_day])
    end
  end

  describe "GET show" do
    it "assigns the requested school_day as @school_day" do
      school_day = SchoolDay.create! valid_attributes
      get :show, {:id => school_day.to_param}, valid_session
      assigns(:school_day).should eq(school_day)
    end
  end

  describe "GET new" do
    it "assigns a new school_day as @school_day" do
      get :new, {}, valid_session
      assigns(:school_day).should be_a_new(SchoolDay)
    end
  end

  describe "GET edit" do
    it "assigns the requested school_day as @school_day" do
      school_day = SchoolDay.create! valid_attributes
      get :edit, {:id => school_day.to_param}, valid_session
      assigns(:school_day).should eq(school_day)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SchoolDay" do
        expect {
          post :create, {:school_day => valid_attributes}, valid_session
        }.to change(SchoolDay, :count).by(1)
      end

      it "assigns a newly created school_day as @school_day" do
        post :create, {:school_day => valid_attributes}, valid_session
        assigns(:school_day).should be_a(SchoolDay)
        assigns(:school_day).should be_persisted
      end

      it "redirects to the created school_day" do
        post :create, {:school_day => valid_attributes}, valid_session
        response.should redirect_to(SchoolDay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved school_day as @school_day" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolDay.any_instance.stub(:save).and_return(false)
        post :create, {:school_day => {}}, valid_session
        assigns(:school_day).should be_a_new(SchoolDay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolDay.any_instance.stub(:save).and_return(false)
        post :create, {:school_day => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested school_day" do
        school_day = SchoolDay.create! valid_attributes
        # Assuming there are no other school_days in the database, this
        # specifies that the SchoolDay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SchoolDay.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => school_day.to_param, :school_day => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested school_day as @school_day" do
        school_day = SchoolDay.create! valid_attributes
        put :update, {:id => school_day.to_param, :school_day => valid_attributes}, valid_session
        assigns(:school_day).should eq(school_day)
      end

      it "redirects to the school_day" do
        school_day = SchoolDay.create! valid_attributes
        put :update, {:id => school_day.to_param, :school_day => valid_attributes}, valid_session
        response.should redirect_to(school_day)
      end
    end

    describe "with invalid params" do
      it "assigns the school_day as @school_day" do
        school_day = SchoolDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => school_day.to_param, :school_day => {}}, valid_session
        assigns(:school_day).should eq(school_day)
      end

      it "re-renders the 'edit' template" do
        school_day = SchoolDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => school_day.to_param, :school_day => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested school_day" do
      school_day = SchoolDay.create! valid_attributes
      expect {
        delete :destroy, {:id => school_day.to_param}, valid_session
      }.to change(SchoolDay, :count).by(-1)
    end

    it "redirects to the school_days list" do
      school_day = SchoolDay.create! valid_attributes
      delete :destroy, {:id => school_day.to_param}, valid_session
      response.should redirect_to(school_days_url)
    end
  end

end
